### ISSUE TITLE
error in code

### ISSUE THREAD

**Issue by ppt900** [Zongwei97/UnTrack#8]
Is there an error in this code? It should calculate the gradients of both the RGB modality and the DTE modality, then concatenate them, instead of calculating the DTE twice. This seems different from what’s described in the paper.

![image](https://github.com/user-attachments/assets/699d87b8-6337-4fef-a46c-351f7b42330f)

**Comment by Zongwei97** [comment]
Yes, you are correct.

Our initial goal was to implement fusion between RGB and X gradients. However, when polishing the code, we also discovered the error that you mentioned in our computation of the RGB gradient, which resulted in it being identical to the X gradient.

Since the performance results were obtained using this code, we have decided to release the code as is...

However, we think both methods should achieve similar performance...
